/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WRouteImport } from './routes/w'
import { Route as NRouteImport } from './routes/n'
import { Route as KRouteImport } from './routes/k'
import { Route as GRouteImport } from './routes/g'
import { Route as IndexRouteImport } from './routes/index'

const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const NRoute = NRouteImport.update({
  id: '/n',
  path: '/n',
  getParentRoute: () => rootRouteImport,
} as any)
const KRoute = KRouteImport.update({
  id: '/k',
  path: '/k',
  getParentRoute: () => rootRouteImport,
} as any)
const GRoute = GRouteImport.update({
  id: '/g',
  path: '/g',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/g': typeof GRoute
  '/k': typeof KRoute
  '/n': typeof NRoute
  '/w': typeof WRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/g': typeof GRoute
  '/k': typeof KRoute
  '/n': typeof NRoute
  '/w': typeof WRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/g': typeof GRoute
  '/k': typeof KRoute
  '/n': typeof NRoute
  '/w': typeof WRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/g' | '/k' | '/n' | '/w'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/g' | '/k' | '/n' | '/w'
  id: '__root__' | '/' | '/g' | '/k' | '/n' | '/w'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GRoute: typeof GRoute
  KRoute: typeof KRoute
  NRoute: typeof NRoute
  WRoute: typeof WRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n': {
      id: '/n'
      path: '/n'
      fullPath: '/n'
      preLoaderRoute: typeof NRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k': {
      id: '/k'
      path: '/k'
      fullPath: '/k'
      preLoaderRoute: typeof KRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g': {
      id: '/g'
      path: '/g'
      fullPath: '/g'
      preLoaderRoute: typeof GRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GRoute: GRoute,
  KRoute: KRoute,
  NRoute: NRoute,
  WRoute: WRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
